### ISSUE TITLE
Does it work? Any docs?

### ISSUE THREAD

**Issue by justinmchase** [my-hotel-manager/elasticsearch-memory-server#20]
^

**Comment by nksen** [comment]
It definitely works - we haven't written any docs as it's currently used as an internal Dev tool, however it's heavily inspired by https://github.com/nodkz/mongodb-memory-server so those docs may be helpful

**Comment by justinmchase** [comment]
Because you published a .d.ts file with the package I was able to easily just import it and figure it out. I am familiar with the mongodb library referenced in the readme so it was indeed pretty intuitive! Of course I hit an issue on windows but that is a different matter.
